name: Update Schema with Replacements

on:
  push:
    branches:
      - main  # Triggers when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Switch to stable-web branch or create it if it doesn't exist
      - name: Switch to stable-web branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout main
          git pull origin main
          git fetch --all
          if git rev-parse --verify stable-web; then
            git checkout stable-web
          else
            git checkout -b stable-web
          fi

      # Step to apply multiple replacements from a reference file with escaping
      - name: Apply find & replace with escaping
        run: |
          ./replace.sh



      # Commit the changes
      - name: Commit and Push changes
        run: |
          git add .
          git commit -m "Update schema with find & replace pairs $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push --set-upstream origin stable-web